import { useRef, useEffect, useState } from 'react'
import {motion} from 'framer-motion'
import Head from 'next/head'
import DrawBg from '../components/drawBg';


export default function Home() {
  const List = useRef();

  const [showAbout, setAbout] = useState(false)
  const [showQuestion, setQuestion] = useState(false)
  const [reload, setReload] = useState(0)
  const [fontSize, setFontSize] = useState(16)
  const [bgColour, setBgColour] = useState('lightGrey')

  const getRandom = (min, max) => Math.floor(Math.random()*(max-min+1)+min);

  useEffect(() => {
    // const children = Array.prototype.slice.call( List.current.children );
  
    const children = Array.prototype.slice.call(document.querySelectorAll('ol li, .about-box'))
    children.forEach((item) => {
      item.style.position = 'absolute';
      item.style.left = getRandom(0, window.innerWidth - 200) + 'px';
      item.style.top = getRandom(0, window.innerHeight - 200) + 'px';
    }) 


  }, [showAbout, showQuestion, reload])

  useEffect(() => {
    document.querySelector('html').style.fontSize = fontSize + 'px';
  }, [fontSize])

  useEffect(() => {
    document.querySelector('body').style.backgroundColor = bgColour;
  }, [bgColour])

  const onFontChange = (e) => {
    setFontSize(e.target.value)
  }

  const onBgChange = (e) => {
    setBgColour(e.target.value)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>🌐 Brutalist.Website</h1>

      <ol ref={List}>
        <li><a href="#">Layout</a></li>
        <li><a href="#">Typography</a></li>
        <li><a href="#">Interaction</a></li>
        <li><a href="#">Colours</a></li>
        <li><a href="#" onClick={() => {setAbout(true);setQuestion(true)}}>About</a></li>
      </ol>

      

      {showQuestion && <motion.div className="about-box" drag dragMomentum={false}>
        <h2>🔬 Research Question</h2>
        <p>Investigating the aesthetic signifiers of brutalist web design through the creation of an educational website/interactive experience, as practice-based research.</p>
        <button onClick={() => {setQuestion(false)}}>&times;</button>
      </motion.div>}

      {showAbout && <motion.div className="about-box" drag dragMomentum={false}>
        <h2>🤔 About</h2>
        <p>Feugiat massa amet mauris condimentum eget, sociis conubia ridiculus morbi.</p>
        <button onClick={() => {setAbout(false)}}>&times;</button>
      </motion.div>}

      <DrawBg/>
      <footer>
        <div>
          <button onClick={() => {setReload(reload + 1)}}>♻️ Reload</button>
          <input type="range" min="16" max="30" value={fontSize} onChange={onFontChange} step="0.1" />
          <input type="color" value="#ff0000" value={bgColour} onChange={onBgChange}/>
        </div>
        <div>&copy; 2021</div>
      </footer>
    </div>
  )
}
